version : '3'

services:
    lb:
        build: ./httpd
        ports:
            - "8080:8080"
    server1:
        image: chatapp
        environment:
            - SERVERID=1
    server2:
        image: chatapp
        environment:
            - SERVERID=2
    server3:
        image: chatapp
        environment:
            - SERVERID=3
    server4:
        image: chatapp
        environment:
            - SERVERID=4
    mongodb:
        image: mongo
        volumes:
            - ./mongodb:/data/db
    rds:
        image: redis